### ISSUE TITLE
Too many file handles have been created during initialisation

### ISSUE THREAD

**Issue by RaimisP** [51Degrees/device-detection-dotnet#10]
Running .NET Framework 4.8 in IIS from onprem file 51Degrees-LiteV4.1.hash and getting the following error:

"Too many file handles have been created during initialisation."

Code:

using (var pipeline = new FiftyOne.DeviceDetection.DeviceDetectionPipelineBuilder().UseOnPremise(fileName, null).Build())
{
   using (var data = pipeline.CreateFlowData())
   {
      data.AddEvidence(FiftyOne.Pipeline.Core.Constants.EVIDENCE_QUERY_USERAGENT_KEY, userAgent);
      data.Process();
      var result = data.Get<FiftyOne.DeviceDetection.IDeviceData>();
      var value = result.IsMobile.Value;
      return value;
   }
}

The error is on the first row (the Build method):

FiftyOne.DeviceDetection.Hash.Engine.OnPremise
   at FiftyOne.DeviceDetection.Hash.Engine.OnPremise.Interop.EngineHashSwig..ctor(String fileName, ConfigHashSwig config, RequiredPropertiesConfigSwig properties)
   at FiftyOne.DeviceDetection.Hash.Engine.OnPremise.Wrappers.SwigFactory.<>c.<.ctor>b__4_0(String fileName, IConfigSwigWrapper config, IRequiredPropertiesConfigSwigWrapper requiredProperties)
   at FiftyOne.DeviceDetection.Hash.Engine.OnPremise.Wrappers.SwigFactory.CreateEngine(String fileName, IConfigSwigWrapper config, IRequiredPropertiesConfigSwigWrapper requiredProperties)
   at FiftyOne.DeviceDetection.Hash.Engine.OnPremise.FlowElements.DeviceDetectionHashEngine.RefreshData(String dataFileIdentifier)
   at FiftyOne.Pipeline.Engines.FlowElements.OnPremiseAspectEngineBase`2.AddDataFile(IAspectEngineDataFile dataFile)
   at FiftyOne.DeviceDetection.Shared.FlowElements.OnPremiseDeviceDetectionEngineBase`1.AddDataFile(IAspectEngineDataFile dataFile)
   at FiftyOne.DeviceDetection.Hash.Engine.OnPremise.FlowElements.DeviceDetectionHashEngineBuilder.NewEngine(List`1 properties)
   at FiftyOne.Pipeline.Engines.FlowElements.AspectEngineBuilderBase`2.BuildEngine()
   at FiftyOne.Pipeline.Engines.FlowElements.SingleFileAspectEngineBuilderBase`2.Build()
   at FiftyOne.Pipeline.Engines.FlowElements.SingleFileAspectEngineBuilderBase`2.Build(String datafile, Boolean createTempDataCopy)
   at FiftyOne.DeviceDetection.DeviceDetectionOnPremisePipelineBuilder.ConfigureAndBuild[TBuilder,TEngine](OnPremiseDeviceDetectionEngineBuilderBase`2 builder)
   at FiftyOne.DeviceDetection.DeviceDetectionOnPremisePipelineBuilder.Build()

**Comment by Steve51D** [comment]
Hi @RaimisP, Apologies for the delay in getting back to you on this.
We've been unable to reproduce this problem. Is it something that happens intermittently, or every time?

Are you calling the code above repeatedly? If so, this may be the problem.
The Pipeline is intended to be a singleton for the most part, certainly creating thousands of instances will cause issues.

**Comment by RaimisP** [comment]
Thanks, fixed by creating a singleton.
