### ISSUE TITLE
Crash when targeting AnyCPU 

### ISSUE THREAD

**Issue by Steve51D** [51Degrees/device-detection-dotnet#14]
Following on from #13 

When solution platform is set to 'AnyCPU', the device detection NuGet package will attempt to load the 32-bit native dll for device detection. If a 64-bit process is being used then this will cause an error similar to the following:

```
The type initializer for 'FiftyOne.DeviceDetection.Hash.Engine.OnPremise.Interop.DeviceDetectionHashEngineModulePINVOKE' threw an exception.
at FiftyOne.DeviceDetection.Hash.Engine.OnPremise.Interop.DeviceDetectionHashEngineModulePINVOKE.new_ConfigHashSwig()
at FiftyOne.DeviceDetection.Hash.Engine.OnPremise.Interop.ConfigHashSwig..ctor()
at FiftyOne.DeviceDetection.Hash.Engine.OnPremise.Wrappers.SwigFactory.<>c.<.ctor>b__4_3()
at FiftyOne.DeviceDetection.Hash.Engine.OnPremise.FlowElements.DeviceDetectionHashEngineBuilder.get_SwigConfig()
at FiftyOne.DeviceDetection.Hash.Engine.OnPremise.FlowElements.DeviceDetectionHashEngineBuilder.SetPerformanceProfile(PerformanceProfiles profile)
at FiftyOne.DeviceDetection.DeviceDetectionOnPremisePipelineBuilder.ConfigureAndBuild[TBuilder,TEngine](OnPremiseDeviceDetectionEngineBuilderBase`2 builder)
at FiftyOne.DeviceDetection.DeviceDetectionOnPremisePipelineBuilder.Build()
at project1.Models.FiftyOneDegrees.GetDevice() in C:\Users\user1\source\Workspaces\workspace\project1\project1\Models\FiftyOneDegrees.cs:line 151

The type initializer for 'SWIGExceptionHelper' threw an exception.
at FiftyOne.DeviceDetection.Hash.Engine.OnPremise.Interop.DeviceDetectionHashEngineModulePINVOKE.SWIGExceptionHelper..ctor()
at FiftyOne.DeviceDetection.Hash.Engine.OnPremise.Interop.DeviceDetectionHashEngineModulePINVOKE..cctor()

An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
at FiftyOne.DeviceDetection.Hash.Engine.OnPremise.Interop.DeviceDetectionHashEngineModulePINVOKE.SWIGExceptionHelper.SWIGRegisterExceptionCallbacks_DeviceDetectionHashEngineModule(ExceptionDelegate applicationDelegate, ExceptionDelegate arithmeticDelegate, ExceptionDelegate divideByZeroDelegate, ExceptionDelegate indexOutOfRangeDelegate, ExceptionDelegate invalidCastDelegate, ExceptionDelegate invalidOperationDelegate, ExceptionDelegate ioDelegate, ExceptionDelegate nullReferenceDelegate, ExceptionDelegate outOfMemoryDelegate, ExceptionDelegate overflowDelegate, ExceptionDelegate systemExceptionDelegate)
at FiftyOne.DeviceDetection.Hash.Engine.OnPremise.Interop.DeviceDetectionHashEngineModulePINVOKE.SWIGExceptionHelper..cctor()
```

**Comment by tungntpham** [comment]
Error message has been updated to clarify that specific platform (x86/x64) should be used when building with .NET Framework as anyCPU is not support.
