### ISSUE TITLE
"cannot open shared object file: No such file or directory" with version 4.4.23

### ISSUE THREAD

**Issue by seruminar** [51Degrees/device-detection-dotnet#31]
Hi, me again! We updated to version `4.4.23` to use the navigator values and `UachJsConversionElementBuilder`, but even with `RUN apt install libatomic1` we are getting this again:
```
System.Exception: Failed to load the Device Detection native library, common causes include: 
    - Missing dependencies:
        o On Windows, the Visual C++ runtime is not installed, see the Visual Studio download page for the latest C++ Redistributable: https://visualstudio.microsoft.com/downloads/
        o On Linux, the libatomic shared object is missing. On Debian based distributions, run ‘apt install libatomic1’; on RedHat based distributions, run ‘<yum|dnf> install libatomic’.
    - The DLL file was not copied to the output directory during build, refer to the ‘System.DllNotFoundException’ inner exception for the exact library file name.
    - The incorrect DLL was copied to the output directory, this maybe be caused by the build chain determining the incorrect platform or the incorrect platform has been specified in the build process. If using the dotnet command, see https://docs.microsoft.com/en-us/dotnet/core/rid-catalog to specify the correct runtime. If using Visual Studio, make sure the selected Platform (x86/x64) matches your environment.
    - If building for .NET Framework, the AnyCPU configuration is not supported, make sure to build for the required Platform (x86/x64).
 ---> System.TypeInitializationException: The type initializer for 'FiftyOne.DeviceDetection.Hash.Engine.OnPremise.Interop.DeviceDetectionHashEngineModulePINVOKE' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'SWIGExceptionHelper' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'FiftyOne.DeviceDetection.Hash.Engine.OnPremise.Native.dll' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libFiftyOne.DeviceDetection.Hash.Engine.OnPremise.Native.dll: cannot open shared object file: No such file or directory
   at void FiftyOne.DeviceDetection.Hash.Engine.OnPremise.Interop.DeviceDetectionHashEngineModulePINVOKE+SWIGExceptionHelper.SWIGRegisterExceptionCallbacks_DeviceDetectionHashEngineModule(ExceptionDelegate applicationDelegate, ExceptionDelegate arithmeticDelegate, ExceptionDelegate divideByZeroDelegate, ExceptionDelegate indexOutOfRangeDelegate, ExceptionDelegate invalidCastDelegate, ExceptionDelegate invalidOperationDelegate, ExceptionDelegate ioDelegate, ExceptionDelegate nullReferenceDelegate, ExceptionDelegate outOfMemoryDelegate, ExceptionDelegate overflowDelegate, ExceptionDelegate systemExceptionDelegate)
   at static FiftyOne.DeviceDetection.Hash.Engine.OnPremise.Interop.DeviceDetectionHashEngineModulePINVOKE+SWIGExceptionHelper()
   --- End of inner exception stack trace ---
   at new FiftyOne.DeviceDetection.Hash.Engine.OnPremise.Interop.DeviceDetectionHashEngineModulePINVOKE+SWIGExceptionHelper()
   at static FiftyOne.DeviceDetection.Hash.Engine.OnPremise.Interop.DeviceDetectionHashEngineModulePINVOKE()
   --- End of inner exception stack trace ---
   at IntPtr FiftyOne.DeviceDetection.Hash.Engine.OnPremise.Interop.DeviceDetectionHashEngineModulePINVOKE.new_ConfigHashSwig()
   at new FiftyOne.DeviceDetection.Hash.Engine.OnPremise.Interop.ConfigHashSwig()
   at IConfigSwigWrapper FiftyOne.DeviceDetection.Hash.Engine.OnPremise.Wrappers.SwigFactory+<>c.<.ctor>b__4_7(?)+() => { }
   at T FiftyOne.DeviceDetection.Hash.Engine.OnPremise.Wrappers.SwigFactory.DllExceptionHandler<T>(Func<T> action)
   --- End of inner exception stack trace ---
   at T FiftyOne.DeviceDetection.Hash.Engine.OnPremise.Wrappers.SwigFactory.DllExceptionHandler<T>(Func<T> action)
   at FiftyOne.DeviceDetection.Hash.Engine.OnPremise.Wrappers.SwigFactory()+() => { } [3]
   at IConfigSwigWrapper FiftyOne.DeviceDetection.Hash.Engine.OnPremise.Wrappers.SwigFactory.CreateConfig()
   at IConfigSwigWrapper FiftyOne.DeviceDetection.Hash.Engine.OnPremise.FlowElements.DeviceDetectionHashEngineBuilder.get_SwigConfig()
   at DeviceDetectionHashEngineBuilder FiftyOne.DeviceDetection.Hash.Engine.OnPremise.FlowElements.DeviceDetectionHashEngineBuilder.SetPerformanceProfile(PerformanceProfiles profile)
   at TEngine FiftyOne.DeviceDetection.DeviceDetectionOnPremisePipelineBuilder.ConfigureAndBuild<TBuilder, TEngine>(OnPremiseDeviceDetectionEngineBuilderBase<TBuilder, TEngine> builder)
   at IPipeline FiftyOne.DeviceDetection.DeviceDetectionOnPremisePipelineBuilder.Build()
```

Can you help me figure out what to do here?

**Comment by Sara51D** [comment]
Hi @seruminar , could you please provide us details about your environment and if you have resolved all the issues in the exception message? Thank you.

**Comment by seruminar** [comment]
Hi @Sara51D, thank you for the reply.

The context is that the same environment below is able to use the library without issues at version `4.4.16`.

Target framework: `net6.0`
Base Docker image: `mcr.microsoft.com/dotnet/sdk:6.0`
Build command: `dotnet publish "API.csproj" -c Release -o /app/publish`
Added (relative to our template) RUN command: `RUN apt install libatomic1`

I verified this by branching the previous commit and deploying that, which worked as expected.

Aside from the code changes, the only change is to use version `4.4.23` of the library. There was no change to the Dockerfile, the AWS infrastructure, or the content of the data passed into the library methods.

Issue resolution:
- Missing dependencies:
   - On Windows, the Visual C++ runtime is not installed, see the Visual Studio download page for the latest C++ Redistributable: https://visualstudio.microsoft.com/downloads/
      - We are not on Windows
   - On Linux, the libatomic shared object is missing. On Debian based distributions, run ‘apt install libatomic1’; on RedHat based distributions, run ‘<yum|dnf> install libatomic’.
      - This exists
 - The DLL file was not copied to the output directory during build, refer to the ‘System.DllNotFoundException’ inner exception for the exact library file name.
    - According to the exception the DLL file is being loaded
 - The incorrect DLL was copied to the output directory, this maybe be caused by the build chain determining the incorrect platform or the incorrect platform has been specified in the build process. If using the dotnet command, see https://docs.microsoft.com/en-us/dotnet/core/rid-catalog to specify the correct runtime. If using Visual Studio, make sure the selected Platform (x86/x64) matches your environment.
    - The build chain has not changed
 - If building for .NET Framework, the AnyCPU configuration is not supported, make sure to build for the required Platform (x86/x64).
   - We are not building for .NET Framework

**Comment by Sara51D** [comment]
Thank you for sharing this information @seruminar . Here is the release history and notes from version 4.4.16 to the current version 4.4.23 for your reference. [Releases · 51Degrees/device-detection-dotnet (github.com)](https://github.com/51Degrees/device-detection-dotnet/releases). This particular issue is a common issue so we expanded the error message in version 4.4.17.
Please see the contents of the NuGet package in the image below – these are the files included in the distributed NuGet package. 
The file to look for is libFifityOne.DeviceDetection.Hash.Engine.OnPremise.Native.dll. Could you please check where this file is being copied to and can your application access it?
![image](https://user-images.githubusercontent.com/97543056/235642660-3f7aad42-535e-4cb8-8d46-0c580bfb1e0b.png)

**Comment by seruminar** [comment]
Alright so here is what's in the image with just incrementing the version from `4.4.16` to `4.4.23`:
![7zFM_xIznVO65NX](https://user-images.githubusercontent.com/35008875/235772992-7ae015df-2a42-40d9-b05b-189ca181244a.png)
And here is the same from the base image with version `4.4.16`:
![7zFM_rfgyCbLPdL](https://user-images.githubusercontent.com/35008875/235773067-1073f8c3-c42f-4f79-8ff7-737e4ff02367.png)
The files appear to be in the same folders with the same permissions, and while they don't have version metadata the other DLLs are the expected versions.

I have also tested `4.4.19` and `4.4.20`:
- `4.4.19` works without using the value needed for `UachJsConversionElement` but with the value it complains about the format (the same value works locally with `4.4.23`)
- `4.4.20` fails in the same way above

**Comment by jwrosewell** [comment]
I've not been able to recreate this issue. Here are the steps followed.

1. Using Ubuntu 22.10 with libatomic installed and dotnet SDK version 6.0.

2. Clone this repository and all sub-modules including the LFS data files.

3. Navigate to the `Examples/OnPremise/GettingStarted-Console` folder.

4. Execute `dotnet run` to obtain all the packages and then run the example. Output is as expected.

```
info: FiftyOne.DeviceDetection.Hash.Engine.OnPremise.FlowElements.DeviceDetectionHashEngine[0]
      FlowElement 'DeviceDetectionHashEngine' created.
info: FiftyOne.Pipeline.Core.FlowElements.Pipeline[0]
      Pipeline '14993092' created.
Input values:
        header.user-agent: Mozilla/5.0 (Linux; Android 9; SAMSUNG SM-G960U) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/10.1 Chrome/71.0.3578.99 Mobile Safari/537.36

Results:
        Mobile Device: True
        Platform Name: Android
        Platform Version: 9.0
        Browser Name: Samsung Browser
        Browser Version: 10.1
Matched
        ______________________droid 9; S__________G960U) Apple______________________________________________er/10.1_Chrome/71.0.3_____9 Mobile______________

Input values:
        header.user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36

Results:
        Mobile Device: False
        Platform Name: Windows
        Platform Version: 10.0
        Browser Name: Chrome
        Browser Version: 78
Matched
        __________________________.0; Win64; x64) Apple__________________________________Chrome/78.0.3____108______________

Input values:
        header.user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36
        header.sec-ch-ua-mobile: ?0
        header.sec-ch-ua: " Not A; Brand";v="99", "Chromium";v="98", "Google Chrome";v="98"
        header.sec-ch-ua-platform: "Windows"
        header.sec-ch-ua-platform-version: "14.0.0"

Results:
        Mobile Device: False
        Platform Name: Windows
        Platform Version: 11.0
        Browser Name: Chrome
        Browser Version: 98
Matched
        ?0
        _Windows"
        ________________________10.0;______; x64) Apple_________________________________ Chrome/98._________2 Safari/537.36
        _____ows""14_____
        ________________________________________________________e";v="98"?0"________

info: FiftyOne.DeviceDetection.Examples.OnPremise.GettingStartedConsole.Program[0]
      Using a 'Lite' data file created '02/01/2023 00:00:00' from location '/mnt/c/Users/james/device-detection-dotnet/FiftyOne.DeviceDetection/device-detection-cxx/device-detection-data/51Degrees-LiteV4.1.hash'
warn: FiftyOne.DeviceDetection.Examples.OnPremise.GettingStartedConsole.Program[0]
      This example is using a data file that is more than 30 days old. A more recent data file may be needed to correctly detect the latest devices, browsers, etc. The latest lite data file is available from the device-detection-data repository on GitHub https://github.com/51Degrees/device-detection-data. Find out about the Enterprise data file, which includes automatic daily updates, on our pricing page: https://51degrees.com/pricing
warn: FiftyOne.DeviceDetection.Examples.OnPremise.GettingStartedConsole.Program[0]
      This example is using the 'Lite' data file. This is used for illustration, and has limited accuracy and capabilities. Find out about the Enterprise data file on our pricing page: https://51degrees.com/pricing
info: FiftyOne.Pipeline.Core.FlowElements.Pipeline[0]
      Pipeline '14993092' disposed.
info: FiftyOne.DeviceDetection.Hash.Engine.OnPremise.FlowElements.DeviceDetectionHashEngine[0]
      FlowElement 'DeviceDetectionHashEngine' disposed.
```

Therefore there does not appear to be a problem in the compiled assembly that is being used.

@seruminar can you try follow these steps and provide the output?

**Comment by seruminar** [comment]
Well, it took a really long time and lots of reverse-engineering of the sample code, but here's the result of the app in Linux ECS deployed via Dockerfile:
```
Unhandled exception. System.Exception: Failed to load the Device Detection native library, common causes include:
--
- Missing dependencies:
o On Windows, the Visual C++ runtime is not installed, see the Visual Studio download page for the latest C++ Redistributable: https://visualstudio.microsoft.com/downloads/
o On Linux, the libatomic shared object is missing. On Debian based distributions, run ‘apt install libatomic1’; on RedHat based distributions, run ‘<yum\|dnf> install libatomic’.
- The DLL file was not copied to the output directory during build, refer to the ‘System.DllNotFoundException’ inner exception for the exact library file name.
- The incorrect DLL was copied to the output directory, this maybe be caused by the build chain determining the incorrect platform or the incorrect platform has been specified in the build process. If using the dotnet command, see https://docs.microsoft.com/en-us/dotnet/core/rid-catalog to specify the correct runtime. If using Visual Studio, make sure the selected Platform (x86/x64) matches your environment.
- If building for .NET Framework, the AnyCPU configuration is not supported, make sure to build for the required Platform (x86/x64).
---> System.TypeInitializationException: The type initializer for 'FiftyOne.DeviceDetection.Hash.Engine.OnPremise.Interop.DeviceDetectionHashEngineModulePINVOKE' threw an exception.
---> System.TypeInitializationException: The type initializer for 'SWIGExceptionHelper' threw an exception.
---> System.DllNotFoundException: Unable to load shared library 'FiftyOne.DeviceDetection.Hash.Engine.OnPremise.Native.dll' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libFiftyOne.DeviceDetection.Hash.Engine.OnPremise.Native.dll: cannot open shared object file: No such file or directory
at FiftyOne.DeviceDetection.Hash.Engine.OnPremise.Interop.DeviceDetectionHashEngineModulePINVOKE.SWIGExceptionHelper.SWIGRegisterExceptionCallbacks_DeviceDetectionHashEngineModule(ExceptionDelegate applicationDelegate, ExceptionDelegate arithmeticDelegate, ExceptionDelegate divideByZeroDelegate, ExceptionDelegate indexOutOfRangeDelegate, ExceptionDelegate invalidCastDelegate, ExceptionDelegate invalidOperationDelegate, ExceptionDelegate ioDelegate, ExceptionDelegate nullReferenceDelegate, ExceptionDelegate outOfMemoryDelegate, ExceptionDelegate overflowDelegate, ExceptionDelegate systemExceptionDelegate)
at FiftyOne.DeviceDetection.Hash.Engine.OnPremise.Interop.DeviceDetectionHashEngineModulePINVOKE.SWIGExceptionHelper..cctor()
--- End of inner exception stack trace ---
at FiftyOne.DeviceDetection.Hash.Engine.OnPremise.Interop.DeviceDetectionHashEngineModulePINVOKE.SWIGExceptionHelper..ctor()
at FiftyOne.DeviceDetection.Hash.Engine.OnPremise.Interop.DeviceDetectionHashEngineModulePINVOKE..cctor()
--- End of inner exception stack trace ---
at FiftyOne.DeviceDetection.Hash.Engine.OnPremise.Interop.DeviceDetectionHashEngineModulePINVOKE.new_ConfigHashSwig()
at FiftyOne.DeviceDetection.Hash.Engine.OnPremise.Interop.ConfigHashSwig..ctor()
at FiftyOne.DeviceDetection.Hash.Engine.OnPremise.Wrappers.SwigFactory.<>c.<.ctor>b__4_7()
at FiftyOne.DeviceDetection.Hash.Engine.OnPremise.Wrappers.SwigFactory.DllExceptionHandler[T](Func`1 action)
--- End of inner exception stack trace ---
at FiftyOne.DeviceDetection.Hash.Engine.OnPremise.Wrappers.SwigFactory.DllExceptionHandler[T](Func`1 action)
at FiftyOne.DeviceDetection.Hash.Engine.OnPremise.Wrappers.SwigFactory.<>c.<.ctor>b__4_3()
at FiftyOne.DeviceDetection.Hash.Engine.OnPremise.Wrappers.SwigFactory.CreateConfig()
at FiftyOne.DeviceDetection.Hash.Engine.OnPremise.FlowElements.DeviceDetectionHashEngineBuilder.get_SwigConfig()
at FiftyOne.DeviceDetection.Hash.Engine.OnPremise.FlowElements.DeviceDetectionHashEngineBuilder.SetPerformanceProfile(PerformanceProfiles profile)
at FiftyOne.DeviceDetection.DeviceDetectionOnPremisePipelineBuilder.ConfigureAndBuild[TBuilder,TEngine](OnPremiseDeviceDetectionEngineBuilderBase`2 builder)
at FiftyOne.DeviceDetection.DeviceDetectionOnPremisePipelineBuilder.Build()
at FiftyOne.DeviceDetection.Examples.OnPremise.GettingStartedConsole.Program.Example.Run(String dataFile, ILoggerFactory loggerFactory, TextWriter output) in /Examples/OnPremise/GettingStarted-Console/Program.cs:line 57
at FiftyOne.DeviceDetection.Examples.OnPremise.GettingStartedConsole.Program.Main(String[] args) in /Examples/OnPremise/GettingStarted-Console/Program.cs:line 174
```

I had to contend with the following issues:
- `TreatWarningsAsErrors` caused warnings to fail the build. Warnings aren't errors so that was very confusing.
- It wasn't clear that the rather unsafe `ExampleUtils.FindFile` function needed some file outside of the project.
- The stuff inside `FiftyOne.DeviceDetection/device-detection-cxx` caused very deep paths which fails Docker builds. I deleted those directories.

Here is the Dockerfile:
```
FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app1
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /
COPY . .
RUN dotnet restore "Examples/OnPremise/GettingStarted-Console/GettingStarted-Console.csproj"
WORKDIR "/Examples/OnPremise/GettingStarted-Console"

RUN dotnet build "GettingStarted-Console.csproj" -c Release -o /app1/build

WORKDIR "/Examples/OnPremise/GettingStarted-Console"
FROM build AS publish
RUN dotnet publish "GettingStarted-Console.csproj" -c Release -o /app1/publish

FROM base AS final
WORKDIR /app1
COPY --from=publish /app1/publish .
COPY --from=build "/FiftyOne.DeviceDetection/device-detection-cxx" .

RUN apt-get update && apt-get install -y --no-install-recommends curl

RUN apt install libatomic1

ENTRYPOINT ["/bin/sh", "-c" , "exec dotnet FiftyOne.DeviceDetection.Examples.OnPremise.GettingStartedConsole.dll"]
```

All the stuff is there:
![7zFM_K6q6uoVB4M](https://github.com/51Degrees/device-detection-dotnet/assets/35008875/68b4e197-e5f6-49ff-8e9b-c5fe9c925d30)

The OS again is Amazon Linux 2, which is a mixture of Fedora and Red Hat.

**Comment by Sara51D** [comment]
Thank you @seruminar for sharing these details.
We automatically test and build packages for the environments listed on the tested versions page here : [http://51degrees.com/documentation/4.4/_info__tested_versions.html]

This does not currently include Linux ECS. This does not mean the solution will not work on other environments, only that the packages are not built for these environments.

Now that we understand you are targeting Linux ECS it is likely that the pre-built packages for Ubuntu are not compatible. Therefore you'll need to build the native assemblies specifically for your target environment.

We are in the process of refreshing the dotNet repository so that our community of users can add additional environments to the build and test pipelines. We expect the dotnet repositories to be refactored in June at which point you can provide pull requests for additional Linux environments.

**Comment by seruminar** [comment]
Thank you for that link @Sara51D, it does seem to make a difference. First I confused things with needing to deploy to ECS; it's enough to build and run the Dockerfile locally to see the failing output. Since `sdk:6.0` uses `Debian 11`, I swapped to `sdk:6.0-jammy` which uses `Ubuntu 22.04`. That produced some working output:
```
info: FiftyOne.DeviceDetection.Hash.Engine.OnPremise.FlowElements.DeviceDetectionHashEngine[0]
      FlowElement 'DeviceDetectionHashEngine' created.
info: FiftyOne.Pipeline.Core.FlowElements.Pipeline[0]
      Pipeline '14993092' created.
Input values:
        header.user-agent: Mozilla/5.0 (Linux; Android 9; SAMSUNG SM-G960U) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/10.1 Chrome/71.0.3578.99 Mobile Safari/537.36

Results:
        Mobile Device: True
        Platform Name: Android
        Platform Version: 9.0
        Browser Name: Samsung Browser
        Browser Version: 10.1
Matched
        ______________________droid 9; S__________G960U) Apple______________________________________________er/10.1_Chrome/71.0.3_____9 Mobile______________

Input values:
        header.user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36

Results:
        Mobile Device: False
        Platform Name: Windows
        Platform Version: 10.0
        Browser Name: Chrome
        Browser Version: 78
Matched
        __________________________.0; Win64; x64) Apple__________________________________Chrome/78.0.3____108______________

Input values:
        header.user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36
        header.sec-ch-ua-mobile: ?0
        header.sec-ch-ua: " Not A; Brand";v="99", "Chromium";v="98", "Google Chrome";v="98"
        header.sec-ch-ua-platform: "Windows"
        header.sec-ch-ua-platform-version: "14.0.0"

Results:
        Mobile Device: False
        Platform Name: Windows
        Platform Version: 11.0
        Browser Name: Chrome
        Browser Version: 98
Matched
        ?0
        _Windows"
        ________________________10.0;______; x64) Apple_________________________________ Chrome/98._________2 Safari/537.36
        _____ows""14_____
        ________________________________________________________e";v="98"?0"________

info: FiftyOne.DeviceDetection.Examples.OnPremise.GettingStartedConsole.Program[0]
      Using a 'Lite' data file created '02/01/2023 00:00:00' from location '/app1/device-detection-data/51Degrees-LiteV4.1.hash'
warn: FiftyOne.DeviceDetection.Examples.OnPremise.GettingStartedConsole.Program[0]
      This example is using a data file that is more than 30 days old. A more recent data file may be needed to correctly detect the latest devices, browsers, etc. The latest lite data file is available from the device-detection-data repository on GitHub https://github.com/51Degrees/device-detection-data. Find out about the Enterprise data file, which includes automatic daily updates, on our pricing page: https://51degrees.com/pricing
warn: FiftyOne.DeviceDetection.Examples.OnPremise.GettingStartedConsole.Program[0]
      This example is using the 'Lite' data file. This is used for illustration, and has limited accuracy and capabilities. Find out about the Enterprise data file on our pricing page: https://51degrees.com/pricing
info: FiftyOne.Pipeline.Core.FlowElements.Pipeline[0]
      Pipeline '14993092' disposed.
info: FiftyOne.DeviceDetection.Hash.Engine.OnPremise.FlowElements.DeviceDetectionHashEngine[0]
      FlowElement 'DeviceDetectionHashEngine' disposed.
```

I guess it may be confusing when the exception message mentions `On Debian based distributions` and I was using Debian itself. I'm going to try this with the full app and see if that's a good way forward.

**Comment by Sara51D** [comment]
Thank you @seruminar for this information and for confirming that the solution works. We had added an error message which we thought would be more helpful to people, but it turns out the message wasn't quite complete. It appears that modifying the exception test to advise to verify the .net SDK version and release would have provided additional information. If you are in agreement then we can propose a revised error message and get back to you shortly.

**Comment by seruminar** [comment]
Yes I think having the link for more details would be more robust, it would be easier to update and you could have a detailed explanation there. Possibly you could add a check for the OS version and add that that the current OS may not be supported and output what it is (I understand this may not be reliable). As a user, the message is already detailed but it's misleading because it seems exhaustive, when in fact there are hidden variables that cause a failure. As another example, I wonder if this would work in an ARM64 environment.

**Comment by Artur51D** [comment]
Hi @seruminar,
Could you please review of the revised error message in the below pull request and let me know if you have any feedback?
https://github.com/51Degrees/device-detection-dotnet/pull/34

**Comment by seruminar** [comment]
Hey @Artur51D that looks good and informative to me! Thank you!
